   BEGIN OPEN ? FOR SELECT SYSDATE,
  TMP.OWNER,
  TMP.TABLE_NAME,
  TMP.TABLESPACE_NAME,
  TMP.NUM_ROWS,
  TMP.BLOCKS,
  TMP.AVG_SPACE,
  TMP.AVG_ROW_LEN
FROM all_tables tmp
WHERE TMP.OWNER NOT IN ('SYS','SYSMAN','SYSTEM','WMSYS','DBSNMP','EXFSYS','CTXSYS','XDB','ORDSYS','MDSYS','OLAPSYS','WKSYS','OUTLN')
AND tablespace_name not in ('SYSAUX','SYSTEM'); end;